version: '3'
services:
  web:
    image: joe/front-end:1.0
    build: 
      context: ./docker
      dockerfile: Dockerfile
    container_name: web-dev
    depends_on:
      - api
    volumes:
      - "./app:/app"
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:35729:35729"
    command: gulp
  api:
    image: joe/back-end:1.0
    build: 
      context: ./docker
      dockerfile: server.Dockerfile
    container_name: api-dev
    volumes:
      - "./server:/server"
    ports:
      - "127.0.0.1:8080:8080"
    command: npm start

    